spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library
    username: root
    password: alaa22
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
